FROM golang:1.18 as builder

RUN mkdir /app
RUN chmod 700 /app

RUN git clone -b main https://github.com/helmutkemper/flight.git /app

WORKDIR /app

ARG CGO_ENABLED=0
#RUN go mod tidy
RUN go build -o /app/main /app/cmd/proxyReverse/main.go

EXPOSE 9999

CMD ["/app/main"]

# git clone -b main https://github.com/helmutkemper/flight.git /app
